Models/HeroViewModel.cs
namespace ibrahimcmsuppgift.Models;

public class HeroViewModel
{
	public string Title { get; set; }
	public string Subtitle { get; set; }
	public string ImageUrl { get; set; }
	public string ButtonText { get; set; }
	public string ButtonLink { get; set; }
}

Models/HomePageViewModel.cs
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Strings;

public class HomePageViewModel : PublishedContentWrapped
{
	public HomePageViewModel(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
		: base(content, publishedValueFallback)
	{
	}

	public string HeroTitle { get; set; }
	public string HeroDescription { get; set; }
	public string HeroButtonText { get; set; }
	public string HeroImageUrl { get; set; }

	public string AboutUsTitle { get; set; }
	public IHtmlEncodedString AboutUsContent { get; set; }

	public string OurServicesTitle { get; set; }
	public IEnumerable<IPublishedContent> OurServicesList { get; set; }

	public string RecentProjectsTitle { get; set; }
	public IEnumerable<IPublishedContent> RecentProjectsList { get; set; }

	public string SuccessStoryTitle { get; set; }
	public string FooterText { get; set; }

}

Models/NavBarViewModel.cs
namespace ibrahimcmsuppgift.Models;

public class NavBarViewModel
{
	public string Title { get; set; }
	public string Url { get; set; }
}

Controllers/AboutUsPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class AboutUsPageController : RenderController
{
	public AboutUsPageController(ILogger<AboutUsPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
		: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}

	public override IActionResult Index()
	{

		return CurrentTemplate(CurrentPage);
	}
}

Controllers/ContactUsPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class ContactUsPageController : RenderController
{
	public ContactUsPageController(ILogger<ContactUsPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
	: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}

	public override IActionResult Index()
	{

		return CurrentTemplate(CurrentPage);
	}
}

Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Web.Common.PublishedModels;
using Umbraco.Cms.Core.Models.PublishedContent;

namespace ibrahimcmsuppgift.Controllers;

public class HomePageController : RenderController
{
	private readonly IPublishedValueFallback _publishedValueFallback;

	public HomePageController(
		ILogger<HomePageController> logger,
		ICompositeViewEngine compositeViewEngine,
		IUmbracoContextAccessor umbracoContextAccessor,
		IPublishedValueFallback publishedValueFallback 
	)
		: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
		_publishedValueFallback = publishedValueFallback;
	}

	public override IActionResult Index()
	{
		var homePage = CurrentPage as HomePage;

		if (homePage == null)
		{
			return NotFound();
		}

		var model = new HomePageViewModel(CurrentPage, _publishedValueFallback)
		{
			HeroTitle = homePage.HeroTitle,
			HeroDescription = homePage.HeroDescription,
			HeroButtonText = homePage.HeroButtonText,
			HeroImageUrl = homePage.HeroImage?.Url(),

			AboutUsTitle = homePage.AboutUsTitle,
			AboutUsContent = homePage.AboutUsContent,

			OurServicesTitle = homePage.OurServicesTitle,
			OurServicesList = homePage.OurServicesList,

			RecentProjectsTitle = homePage.RecentProjectsTitle,
			RecentProjectsList = homePage.RecentProjectsContentPicker,

			SuccessStoryTitle = homePage.SuccessStoryTitle,
			FooterText = homePage.FooterText
		};

		return CurrentTemplate(model);
	} 
}

Controllers/OurProjectListPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class OurProjectListPageController : RenderController
{
	public OurProjectListPageController(ILogger<OurProjectListPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
	: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}

	public override IActionResult Index()
	{

		return CurrentTemplate(CurrentPage);
	}
}

Controllers/OurServicesListPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class OurServicesListPageController : RenderController
{
	public OurServicesListPageController(ILogger<OurServicesListPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
		: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}

	public override IActionResult Index()
	{

		return CurrentTemplate(CurrentPage);
	}
}

Controllers/ProjectPostPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class ProjectPostPageController : RenderController
{
	public ProjectPostPageController(ILogger<ProjectPostPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
		: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}
	public override IActionResult Index()
	{
		return CurrentTemplate(CurrentPage);
	}
}

Controllers/ServicePostPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace ibrahimcmsuppgift.Controllers;
public class ServicePostPageController : RenderController
{
	public ServicePostPageController(ILogger<ServicePostPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
		: base(logger, compositeViewEngine, umbracoContextAccessor)
	{
	}

	public override IActionResult Index()
	{

		return CurrentTemplate(CurrentPage);
	}
}

ViewComponents/ContactViewComponent.cs
//using Microsoft.AspNetCore.Mvc;

//namespace ibrahimcmsuppgift.ViewComponents;

//public class ContactViewComponent : ViewComponent
//{
//}

ViewComponents/FooterViewComponent.cs
//using Microsoft.AspNetCore.Mvc;

//namespace ibrahimcmsuppgift.ViewComponents;

//public class FooterViewComponent : ViewComponent
//{
//}

ViewComponents/HeroViewComponent.cs
using ibrahimcmsuppgift.Models;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace ibrahimcmsuppgift.ViewComponents;

public class HeroViewComponent : ViewComponent
{
	private readonly IPublishedContentQuery _contentQuery;

	public HeroViewComponent(IPublishedContentQuery contentQuery)
	{
		_contentQuery = contentQuery;
	}

	public IViewComponentResult Invoke()
	{

		var homePage = _contentQuery.ContentAtRoot().OfType<HomePage>().FirstOrDefault();


		var heroViewModel = new HeroViewModel
		{
			Title = homePage.HeroTitle,
			Subtitle = homePage.HeroDescription,
			ImageUrl = homePage.HeroImage?.Url(),
			ButtonText = homePage.HeroButtonText
		};

		return View(heroViewModel);
	}
}

ViewComponents/NavBarViewComponent.cs
using ibrahimcmsuppgift.Models;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core;

namespace ibrahimcmsuppgift.ViewComponents;

public class NavBarViewComponent : ViewComponent
{
	private readonly IPublishedContentQuery _contentQuery;

	public NavBarViewComponent(IPublishedContentQuery contentQuery)
	{
		_contentQuery = contentQuery;
	}

	public IViewComponentResult Invoke()
	{
		var rootContent = _contentQuery.ContentAtRoot().FirstOrDefault();

		if (rootContent == null)
		{
			return Content("No root content found.");
		}

		var navItems = rootContent.Children
			.Where(c => c.IsVisible())
			.Select(c => new NavBarViewModel
			{
				Title = c.Name,
				Url = c.Url()
			})
			.ToList();

		return View(navItems);
	}
}

Views/Partials/blockgrid/area.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridArea>

<div class="umb-block-grid__area"
     data-area-col-span="@Model.ColumnSpan"
     data-area-row-span="@Model.RowSpan"
     data-area-alias="@Model.Alias"
     style="--umb-block-grid--grid-columns: @Model.ColumnSpan;--umb-block-grid--area-column-span: @Model.ColumnSpan; --umb-block-grid--area-row-span: @Model.RowSpan;">
    @await Html.GetBlockGridItemsHtmlAsync(Model)
</div>

Views/Partials/blockgrid/areas.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>
@{
    if (Model?.Areas.Any() != true) { return; }
}

<div class="umb-block-grid__area-container"
     style="--umb-block-grid--area-grid-columns: @(Model.AreaGridColumns?.ToString() ?? Model.GridColumns?.ToString() ?? "12");">
    @foreach (var area in Model.Areas)
    {
        @await Html.GetBlockGridItemAreaHtmlAsync(area)
    }
</div>

Views/Partials/blockgrid/default.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridModel>
@{
    if (Model?.Any() != true) { return; }
}

<div class="umb-block-grid"
     data-grid-columns="@(Model.GridColumns?.ToString() ?? "12");"
     style="--umb-block-grid--grid-columns: @(Model.GridColumns?.ToString() ?? "12");">
    @await Html.GetBlockGridItemsHtmlAsync(Model)
</div>

Views/Partials/blockgrid/items.cshtml
@using Umbraco.Cms.Core.Models.Blocks
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<IEnumerable<BlockGridItem>>
@{
    if (Model?.Any() != true) { return; }
}

<div class="umb-block-grid__layout-container">
    @foreach (var item in Model)
    {
        
        <div
            class="umb-block-grid__layout-item"
            data-content-element-type-alias="@item.Content.ContentType.Alias"
            data-content-element-type-key="@item.Content.ContentType.Key"
            data-element-udi="@item.ContentUdi"
            data-col-span="@item.ColumnSpan"
            data-row-span="@item.RowSpan"
            style=" --umb-block-grid--item-column-span: @item.ColumnSpan; --umb-block-grid--item-row-span: @item.RowSpan; ">
            @{
                var partialViewName = "blockgrid/Components/" + item.Content.ContentType.Alias;
                try
                {
                    @await Html.PartialAsync(partialViewName, item)
                }
                catch (InvalidOperationException)
                {
                    <p>
                        <strong>Could not render component of type: @(item.Content.ContentType.Alias)</strong>
                        <br/>
                        This likely happened because the partial view <em>@partialViewName</em> could not be found.
                    </p>
                }
            }
        </div>
    }
</div>

Views/Partials/blocklist/default.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (Model?.Any() != true) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("blocklist/Components/" + data.ContentType.Alias, block)
    }
</div>

Views/Shared/Components/Hero/Default.cshtml
@model HeroViewModel

<section class="hero-section" style="background-image: url('@Model.ImageUrl');">
    <div class="hero-content">
        <h1>@Model.Title</h1>
        <p>@Model.Subtitle</p>
        @if (!string.IsNullOrEmpty(Model.ButtonText))
        {
            <a href="@Model.ButtonLink" class="btn-primary">@Model.ButtonText</a>
        }
    </div>
</section>

Views/Shared/Components/NavBar/Default.cshtml
@model IEnumerable<NavBarViewModel>

<header>
    <div class="top-bar">
        <div class="container">
            <span class="address">Klarabergsviadukten 90, 111 64 Stockholm</span>
        </div>
    </div>

    <div class="logo-nav">
        <div class="logo">
            <img src="/image/Brand.png" alt="Onatrix Logo" />
        </div>
        <nav>
            <ul class="nav-links">
                @foreach (var item in Model)
                {
                    <li><a href="@item.Url">@item.Title</a></li>
                }
            </ul>
            <div class="search-icon">
                <a href="#"><i class="icon-search"></i></a>
            </div>
        </nav>
    </div>
</header>

Views/aboutUsPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "master.cshtml";
}

Views/contactUsPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}

Views/homePage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<HomePageViewModel>

@{
    Layout = "master.cshtml";
}



    @await Component.InvokeAsync("Hero")
<div class="container">


    <!-- About Us Section -->
    <section class="about-us">
        <div class="about-content">
            <h4>ABOUT US</h4>
            <h2>@Model.AboutUsTitle</h2>
            <p>"@Model.AboutUsContent"</p>
        </div>
        <div class="call-back-form">
            <!-- Placeholder for a call-back form -->
            <h3>Request a call back</h3>
            <form>
                <label for="name">Name</label>
                <input type="text" id="name" name="name">
                <label for="email">Email</label>
                <input type="email" id="email" name="email">
                <label for="phone">Phone</label>
                <input type="tel" id="phone" name="phone">
                <label for="service">Service</label>
                <select id="service" name="service">
                    <option value="financial-consulting">Financial Consulting</option>
                    <!-- Add other options as necessary -->
                </select>
                <button type="submit">Submit</button>
            </form>
        </div>
    </section>

@*     <!-- Our Services Section -->
    <section class="our-services">
        <h4>OUR SERVICES</h4>
        <h2>@Model.OurServicesTitle</h2>
        <div class="services-grid">
            @foreach (var service in Model.OurServicesList)
            {
                <div class="service-item">
                    <img src="@service." alt="@service.Name" />
                    <h3>@service.Name</h3>
                    <p>@service.Value("serviceDescription")</p>
                </div>
            }
        </div>
    </section>
 *@
    <!-- Trust Section -->
@*     <section class="trust-section">
        <h4>@Model.TrustClientTitle</h4>
        <h2>@Model.TrustClientCount+ clients</h2>
        <p>@Model.TrustClientDescription</p>
        <a href="#" class="btn-primary">Read our story</a>
    </section> *@

    <!-- Success Stories Section -->
@*     <section class="success-stories" style="background-color: #4F5955;">
        <h4>SUCCESS STORIES</h4>
        <h2>@Model.SuccessStoryTitle</h2>
        <div class="stats">
            <div class="stat-item">
                <h3>@Model.SuccessStoryStats.ClientsServed</h3>
                <p>More than 100 customers served</p>
            </div>
            <div class="stat-item">
                <h3>@Model.SuccessStoryStats.ProjectsCompleted</h3>
                <p>More than 370 projects completed</p>
            </div>
            <div class="stat-item">
                <h3>@Model.SuccessStoryStats.BranchesOpened</h3>
                <p>More than 125 branches worldwide</p>
            </div>
        </div>
    </section>

    <!-- Recent Projects Section -->
    <section class="recent-projects">
        <h4>OUR PROJECTS</h4>
        <h2>@Model.RecentProjectsTitle</h2>
        <div class="projects-grid">
            @foreach (var project in Model.RecentProjectsList)
            {
                <div class="project-item">
                    <img src="@project.Value("projectImage").Url()" alt="@project.Name" />
                    <h3>@project.Name</h3>
                    <p>@project.Value("projectDescription")</p>
                </div>
            }
        </div>
    </section> *@
</div>


<style>
    .about-us {
        display: flex;
        justify-content: space-between;
        margin: 40px 0;
    }

    .about-content {
        width: 60%;
    }

    .call-back-form {
        width: 35%;
        background-color: #4F5955;
        padding: 20px;
        color: white;
    }

    .services-grid, .projects-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        margin-top: 40px;
    }

    .service-item, .project-item {
        text-align: center;
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 5px;
    }

    .trust-section {
        text-align: center;
        margin: 40px 0;
    }

    .success-stories {
        padding: 40px;
        color: white;
    }

    .stats {
        display: flex;
        justify-content: space-around;
        margin-top: 20px;
    }

    .stat-item {
        text-align: center;
    }

    .btn-primary {
        background-color: #4F5955;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
    }

        .btn-primary:hover {
            background-color: #333;
        }
</style>

Views/master.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}

<!DOCTYPE html>
<html>
<head>
	<title>Page Title</title>
	<link href="/css/style.css" rel="stylesheet" />
</head>
<body>
	@await Component.InvokeAsync("NavBar")
	@RenderBody()
	@* @await Component.InvokeAsync("Footer") *@
</body>
</html>

Views/ourProjectsListPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "master.cshtml";
}

Views/ourServiceListPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "master.cshtml";
}

Views/projectPostPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "master.cshtml";
}

Views/servicePostPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "master.cshtml";
}